{
  "files": {
    "12_lambda.py": [
      {
        "id": "fd3392cf-0c32-495d-a852-94e6d1790096",
        "line": 6,
        "version": 243,
        "index": 64
      }
    ],
    "21.errors.py": [
      {
        "id": "b95a0a83-830e-46fd-8a45-0f9fd2ae11f8",
        "line": 1,
        "version": 9,
        "index": 0
      }
    ]
  }
}